name: s07_action_04

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v4
            - name: Configurar Git
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Inicio
              run: |
                sleep 10
                echo "Ok"

            - name: "Crear un archivo automáticamente"
              run: touch generado.txt

            - name: "Agregar contenido a un archivo HTML"
              run: echo "<p>Actualizado</p>" >> index.html

            - name: "Agregar fecha de modificación al HTML"
              run: echo "<!-- $(date) -->" >> index.html

            - name: Commit
              run: |
                git add .
                git commit -m "Actualizacion auto"

            - name: Push
              run: |
                git push origin main