name: s07_action_03

on:
    workflow_dispatch:

jobs:
    Mi_job:
        runs-on: ubuntu-latest

        steps:

            - name: "Run echo command"
              run: echo "Ok"

            - name: "Tiempo de ejecución"
              run: date

            - name: "Contenido"
              run: ls -la

            - name: "Rama actual"
              run: echo "Rama ${{ github.ref }}"

            - name: Se ejecuto en Desarrollo
              if: github.ref == 'refs/heads/develope'
              run: echo "Modo desarrollo"

            - name: Se ejecuto en Main
              if: github.ref == 'refs/heads/main'
              run: echo "Modo Main"

            - name: Mi for
              run: |
                  for i in 1 2 3 4 5
                  do
                    echo "Numero $i"
                  done

            - uses: actions/checkout@v4
            - name: Mi for html
              run: |
                  for archivo in $(find . -name "*.html")
                  do
                    echo "$archivo"
                  done