name: s07_action_03

on:
    workflow_dispatch:

jobs:
    Mi_primer_job:
        runs-on: ubuntu-latest

        steps:
            - name: Inicio
              run: |
               sleep 10
               echo "Ok"
               echo "$(date)" >> prueba.txt

            - name: Desarrollo
              if: github.ref == 'refs/heads/develope'
              run: echo "Modo desarrollo"

            - name: Se ejecuto en Main
              if: github.ref == 'refs/heads/main'
              run: echo "Modo Main"