name: s07_action_01

on:
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Comandos Linux
        run: |
          echo "Estoy en Linux"
          pwd
          ls -la

  windows:
    runs-on: windows-latest

    steps:
      - name: Comandos Windows
        run: |
          Write-Host "Estoy en Windows"
          Get-Location
          dir