name: Auto Tag en cada Commit

on:
  push:
    branches:
      - develop # Cambia 'main' por el nombre de tu rama principal si es diferente

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso obligatorio para crear tags

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Crear y subir Tag
        run: |
          # Genera un nombre de tag único usando el short SHA del commit
          TAG_NAME="v1.0.${{ github.run_number }}"
          
          # Configura el usuario de Git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@://github.com"
          
          # Crea el tag local y lo sube a GitHub
          git tag $TAG_NAME
          git push origin $TAG_NAME