name: s07_action_04

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: "Run echo command"
              run: echo "Ok"

            - name: "Tiempo de ejecución"
              run: date # echo "Hello ${{ env.MY_ENV_VAR }}"

            - name: "Contenido"
              run: ls -la|

            - name: "Rama actual"
              run: echo "Rama ${{ github.ref }}"
