name: s07_action_07

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

env:
  mi_Empresa: "UTP"

jobs:
    mensaje:
        runs-on: ubuntu-latest

        steps:

            - name: "Mensaje empresa"
              run: echo "Hello ${{ env.mi_Empresa }}"