name: s07_action_07

on:
  workflow_dispatch:
  schedule:
    - cron: '1 12 * * *'

env:
  mi_Empresa: "UTP"

jobs:
    mensaje:
        runs-on: ubuntu-latest

        steps:

          - name: Fecha
            run: date

          - name: Mensaje empresa
            run: echo "Hello ${{ env.mi_Empresa }}"